<div class="footer_left_text">
    <style>
        .page-footer {
            background: #1c1b1b;
            margin-top: auto;
        }

        .footer.content {
            border: none;
            margin-top: 25px;
            padding-bottom: 25px;
            padding-top: 25px;
        }
    /* </style>
    <style> */
    </style>
    <div class="footer-contain">
        <div class="footer-main">
            <div class="footer-main-left">
                <div class="linklist-container">
                    <button
                        class="accordion"><span></span>DISCOVER</button>
                    <div class="panel">
                        <ul>
                            <li><a href>Stores</a></li>
                            <li><a href>Gift Cards</a></li>
                            <li><a href>Check Gift Card
                                    Balance</a></li>
                            <li><a href>Size Guide</a></li>
                            <li><a href>The Journal</a></li>
                        </ul>
                    </div>
                </div>
                <div class="linklist-container">
                    <button
                        class="accordion"><span></span>HELP</button>
                    <div class="panel">

                        <ul>
                            <li><a href>Contact Us</a></li>
                            <li><a href>Help Centre</a></li>
                            <li><a href>Shipping</a></li>
                            <li><a href>Returns</a></li>
                        </ul>
                    </div>

                </div>

            </div>
            <div class="footer-main-right">
                <h3 class="linklist-title">ACADEMY REWARDS</h3>
                <p class="footer-right-describe">Join Academy
                    Rewards to receive a $10 Welcome reward and
                    earn as you spend. Please allow 24 hours for
                    rewards to appear in your account.</p>
                <div class="slideshow-button">
                    <a href class="buttongroup-item">JOIN
                        NOW</a>
                </div>
                <ul class="footer-social">
                    <li><a href><i
                                class="fa fa-facebook-official"></i></a></li>
                    <li><a href><i
                                class="fa fa-instagram"></i></a></li>
                </ul>
            </div>
        </div>
        <div class="footer-under">
            <select id="currency-dropdown">
                <option value="AUD">AUD $</option>
                <option value="BND">BND $</option>
                <option value="CAD">CAD $</option>
                <option value="CHF">CHF CHF</option>
                <option value="EUR">EUR €</option>
                <option value="GBP">GBP £</option>
                <option value="HKD">HKD $</option>
                <option value="JPY">JPY ¥</option>
                <option value="MYR">MYR RM</option>
                <option value="NZD">NZD $</option>
                <option value="SEK">SEK KR</option>
                <option value="SGD">SGD $</option>
                <option value="TWD">TWD $</option>
                <option value="USD">USD $</option>
            </select>
            <div class="footer-copyright"><a
                    class="footer-storename" href>© 2022 Academy
                    Brand</a></div>
        </div>

    </div>

</div>