<style>
    .page-header{
        z-index: 1000;
    }
</style>

<div class="header_left_text">
    <div class="header-left">
        <ul class="swiper-slide">
            <li class="header-list-left">
                <a class="header-list-items" href>MENS</a>

            </li>
            <li class="header-list-left">
                <a class="header-list-items" href>WOMENS</a>

            </li>
            <li class="header-list-left"><a
                    class="header-list-items" href>KIDS</a>

            </li>
            <li class="header-list-left"><a
                    class="header-list-items"
                    href>ACCESSORIES</a>

            </li>
            <li class="header-list-left"><a
                    class="header-list-items" href>SALE</a>

            </li>
        </ul>

    </div>
    <div class="header-center">
        <img src="<?= $block->getViewFileUrl('images/academybrand-Logo.avif') ?>" alt="Logo" />
    </div>
    <div class="header-right">
        <ul>
            <li><a class="search">SEARCH</a></li>
            <li><a>STORES</a></li>
            <li><a>ACCOUNT</a></li>
            <li><a>REWARDS</a></li>
            <li><a>WISHLIST</a></li>
            <li><a class="header-cart">CART(1)</a></li>
        </ul>
    </div>
</div>