<style>
    .page-header {
        z-index: 1000;
    }
</style>
<div id="overlay"></div>
<div class="header_left_text">
    <div class="header-left">
        <ul class="swiper-slide">
            <li class="header-list-left"><a
                    class="header-list-items" href>BUY 2 SAVE 25%</a>
                <div class="megamenu">
                    <div class="megamenu-inner">
                        <div class="megamenu-list">
                            <div class="megamenu-item">
                                <a class="megamenu-heading" href="">Shop Mens</a>
                            </div>
                            <div class="megamenu-item">
                                <a class="megamenu-heading" href="">Shop Womens</a>
                            </div>
                            <div class="megamenu-item">
                                <a class="megamenu-heading" href="">Shop Rookie</a>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li class="header-list-left">
                <a class="header-list-items" href>MENS</a>
                <div class="megamenu">
                    <div class="megamenu-inner">
                        <div class="megamenu-list">
                            <div class="megamenu-item">
                                <a class="megamenu-heading" href="">Edits</a>
                                <ul class="linklist">
                                    <li class="linklist-item"><a href="#">Event Outfitting</a></li>
                                    <li class="linklist-item"><a href="#">The Holiday Edit</a></li>
                                    <li class="linklist-item"><a href="#">Spring Knits</a></li>
                                    <li class="linklist-item"><a href="#">Colours Of Spring</a></li>
                                    <li class="linklist-item"><a href="#">Best Of Linen</a></li>
                                    <li class="linklist-item"><a href="#">Academy Icons</a></li>
                                </ul>
                            </div>
                            <div class="megamenu-item">
                                <a class="megamenu-heading" href="">Clothing</a>
                                <ul class="linklist">
                                    <li class="linklist-item"><a href="#">View All</a></li>
                                    <li class="linklist-item"><a href="#">New Arrivals</a></li>
                                    <li class="linklist-item"><a href="#">Shorts</a></li>
                                    <li class="linklist-item"><a href="#">Knit Shirts</a></li>
                                    <li class="linklist-item"><a href="#">Short Sleeve Shirts</a></li>
                                    <li class="linklist-item"><a href="#">Long Sleeve Shirts</a></li>
                                    <li class="linklist-item"><a href="#">Tops & Tees</a></li>
                                    <li class="linklist-item"><a href="#">Polo Shirts</a></li>
                                    <li class="linklist-item"><a href="#">Swim</a></li>
                                    <li class="linklist-item"><a href="#">Pants & Chinos</a></li>
                                    <li class="linklist-item"><a href="#">Long Sleeve Tops</a></li>
                                    <li class="linklist-item"><a href="#">Overshirts</a></li>
                                    <li class="linklist-item"><a href="#">Sweats</a></li>
                                    <li class="linklist-item"><a href="#">Jackets & Outerwear</a></li>
                                    <li class="linklist-item"><a href="#">Knitwear</a></li>
                                    <li class="linklist-item"><a href="#">Accessories</a></li>
                                    <li class="linklist-item"><a href="#">Sale</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="megamenu-item">
                            <div class="megamenu-push">
                                <a href="" class="megamenu-pushlink">
                                    <img src="https://academybrand.com/cdn/shop/files/AcademyFrenzyMenuTiles_370x230@2x.jpg?v=1730940541" alt="ảnh 1">
                                    <p>Buy 2% save 25%</p>
                                </a>
                            </div>
                            <div class="megamenu-push">
                                <a href="" class="megamenu-pushlink">
                                    <img src="https://academybrand.com/cdn/shop/files/Megamenu_25S_GetawayEdit_370x230@2x.jpg?v=1726616398" alt="ảnh 1">
                                    <p>Spring kint polos</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li class="header-list-left">
                <a class="header-list-items" href>WOMENS</a>
                <div class="megamenu">
                    <div class="megamenu-inner">
                        <div class="megamenu-list">
                            <div class="megamenu-item">
                                <a class="megamenu-heading" href="">Edits</a>
                                <ul class="linklist">
                                    <li class="linklist-item"><a href="#">Spring Eventwear</a></li>
                                    <li class="linklist-item"><a href="#">The Getaway Edit</a></li>
                                    <li class="linklist-item"><a href="#">The Colour Edit</a></li>
                                    <li class="linklist-item"><a href="#">Live In Linen</a></li>
                                    <li class="linklist-item"><a href="#">Best Sellers</a></li>
                                    <li class="linklist-item"><a href="#">Academy Capsule</a></li>
                                </ul>

                            </div>
                            <div class="megamenu-item">
                                <a class="megamenu-heading" href="">Clothing</a>
                                <ul class="linklist">
                                    <li class="linklist-item"><a href="#">View All</a></li>
                                    <li class="linklist-item"><a href="#">New Arrivals</a></li>
                                    <li class="linklist-item"><a href="#">Shorts</a></li>
                                    <li class="linklist-item"><a href="#">Tanks & Singlets</a></li>
                                    <li class="linklist-item"><a href="#">Short Sleeve Shirts</a></li>
                                    <li class="linklist-item"><a href="#">Long Sleeve Shirts</a></li>
                                    <li class="linklist-item"><a href="#">Tops & Tees</a></li>
                                    <li class="linklist-item"><a href="#">Sets</a></li>
                                    <li class="linklist-item"><a href="#">Dresses</a></li>
                                    <li class="linklist-item"><a href="#">Pants</a></li>
                                    <li class="linklist-item"><a href="#">Sweats</a></li>
                                    <li class="linklist-item"><a href="#">Knitwear</a></li>
                                    <li class="linklist-item"><a href="#">Jackets</a></li>
                                    <li class="linklist-item"><a href="#">Long Sleeve Tops</a></li>
                                    <li class="linklist-item"><a href="#">Accessories</a></li>
                                    <li class="linklist-item"><a href="#">Sale</a></li>
                                </ul>

                            </div>
                        </div>
                        <div class="megamenu-item">
                            <div class="megamenu-push">
                                <a href="" class="megamenu-pushlink">
                                    <img src="https://academybrand.com/cdn/shop/files/AcademyFrenzyMenuTiles2_370x230@2x.jpg?v=1730940541" alt="ảnh 1">
                                    <p>Buy 2% save 25%</p>
                                </a>
                            </div>
                            <div class="megamenu-push">
                                <a href="" class="megamenu-pushlink">
                                    <img src="https://academybrand.com/cdn/shop/files/AcademyFrenzyMenuTiles2_370x230@2x.jpg?v=1730940541" alt="ảnh 1">
                                    <p>Spring sets</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li class="header-list-left">
                <a class="header-list-items" href>KIDS</a>
                <div class="megamenu">
                    <div class="megamenu-inner">
                        <div class="megamenu-list">
                            <div class="megamenu-item">
                                <a class="megamenu-heading" href="">Academy Kids</a>
                                <ul class="linklist">
                                    <li class="linklist-item"><a href="#">View All</a></li>
                                    <li class="linklist-item"><a href="#">New Arrivals</a></li>
                                    <li class="linklist-item"><a href="#">Shirts</a></li>
                                    <li class="linklist-item"><a href="#">Shorts</a></li>
                                    <li class="linklist-item"><a href="#">Tees</a></li>
                                    <li class="linklist-item"><a href="#">Swim</a></li>
                                    <li class="linklist-item"><a href="#">Pants</a></li>
                                    <li class="linklist-item"><a href="#">Tops</a></li>
                                    <li class="linklist-item"><a href="#">Sweats</a></li>
                                    <li class="linklist-item"><a href="#">Jackets</a></li>
                                    <li class="linklist-item"><a href="#">Sale</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="megamenu-item">
                            <div class="megamenu-push">
                                <a href="" class="megamenu-pushlink">
                                    <img src="https://academybrand.com/cdn/shop/files/AcademyFrenzyMenuTiles3_370x230@2x.jpg?v=1730940541" alt="ảnh 1">
                                    <p>Buy 2% save 25%</p>
                                </a>
                            </div>
                            <div class="megamenu-push">
                                <a href="" class="megamenu-pushlink">
                                    <img src="https://academybrand.com/cdn/shop/files/20_OffSSShirts3_370x230@2x.jpg?v=1730070595" alt="ảnh 1">
                                    <p>Spring print shirts</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li class="header-list-left"><a
                    class="header-list-items"
                    href>ACCESSORIES</a>
                <div class="megamenu">
                    <div class="megamenu-inner">
                        <div class="megamenu-list">
                            <div class="megamenu-item">
                                <a class="megamenu-heading" href="">Academy Kids</a>
                                <ul class="linklist">
                                    <li class="linklist-item"><a href="#">Mr Voss Collection</a></li>
                                    <li class="linklist-item"><a href="#">Bags</a></li>
                                    <li class="linklist-item"><a href="#">Hats</a></li>
                                    <li class="linklist-item"><a href="#">Sunglasses</a></li>
                                    <li class="linklist-item"><a href="#">Bottles</a></li>
                                    <li class="linklist-item"><a href="#">Beach Towels</a></li>
                                    <li class="linklist-item"><a href="#">Skincare</a></li>
                                    <li class="linklist-item"><a href="#">Candles</a></li>
                                    <li class="linklist-item"><a href="#">Socks</a></li>
                                    <li class="linklist-item"><a href="#">Belts</a></li>
                                    <li class="linklist-item"><a href="#">Underwear</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="megamenu-item">
                            <div class="megamenu-push">
                                <a href="" class="megamenu-pushlink">
                                    <img src="https://academybrand.com/cdn/shop/files/Megamenu_25S7_370x230@2x.jpg?v=1725940328" alt="ảnh 1">
                                    <p>NEW PREMIUM BAGS</p>
                                </a>
                            </div>
                            <div class="megamenu-push">
                                <a href="" class="megamenu-pushlink">
                                    <img src="https://academybrand.com/cdn/shop/files/02_FEB_Megamenu_GiftCards_370x230@2x.jpg?v=1708649440" alt="ảnh 1">
                                    <p>It’s The Card That Counts</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>

    </div>
    <div class="header-center">
        <img src="<?= $block->getViewFileUrl('images/academybrand-Logo.avif') ?>" alt="Logo" />
    </div>
    <div class="header-right">
        <ul>
            <li>
                <a class="search-btn">SEARCH</a>
                <div class="search" id="search">
                    <div class="search-inner">
                        <div class="search-searchbar">
                            <div class="search-form">
                                <div class="search-inputicon-wrapper">
                                    <svg width="24px" height="24px"
                                        viewBox="0 0 24 24"
                                        version="1.1"
                                        xmlns="http://www.w3.org/2000/svg"
                                        xmlns:xlink="http://www.w3.org/1999/xlink">
                                        <defs></defs>
                                        <g id="Icon/Desktop/Search"
                                            stroke="currentColor"
                                            stroke-width="1" fill="none"
                                            fill-rule="evenodd">
                                            <g
                                                transform="translate(2.000000, 2.000000)"
                                                stroke="currentColor"
                                                class="stroke-color"
                                                stroke-width="2">
                                                <path
                                                    d="M8,14.9987 C12.1457079,14.9987 15.5,11.7494194 15.5,7.74986666 C15.5,3.74942967 12.1458629,0.5 8,0.5 C3.85413706,0.5 0.5,3.74942967 0.5,7.74986666 C0.5,11.7494194 3.85429207,14.9987 8,14.9987 Z"
                                                    id="Stroke-1"></path>
                                                <path
                                                    d="M13.4644,13.4407 L19.4974,19.4737"
                                                    id="Stroke-3"
                                                    stroke-linecap="square"></path>
                                            </g>
                                        </g>
                                    </svg>
                                </div>
                                <input type="search" placeholder="Search...">
                                <div class="search-dropdown">
                                    <div class="seach-dropdown-default">
                                        <div class="dropdown-trending">
                                            <div class="dropdown-trending-title">
                                                <h4>Popular Searches</h4>
                                            </div>
                                            <div class="dropdown-options">
                                                <div class="dropdown-option">
                                                    <a href>volley short</a>
                                                </div>
                                                <div class="dropdown-option">
                                                    <a href>linen</a>
                                                </div>
                                                <div class="dropdown-option">
                                                    <a href>linen shirt</a>
                                                </div>
                                                <div class="dropdown-option">
                                                    <a href>Volley Short</a>
                                                </div>
                                                <div class="dropdown-option">
                                                    <a href>riviera</a>
                                                </div>
                                                <div class="dropdown-option">
                                                    <a href>linen pant</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown-category">
                                            <div class="dropdown-category-items">
                                                <div class="dropdown-category-item">
                                                    <div class="dropdown-category-title">
                                                        Gender
                                                    </div>
                                                    <ul>
                                                        <li><a>Academy Brand</a></li>
                                                        <li><a>Academy Women</a></li>
                                                        <li><a>Academy Kids</a></li>
                                                    </ul>
                                                </div>
                                                <div class="dropdown-category-item">
                                                    <div class="dropdown-category-title">
                                                        Colour
                                                    </div>
                                                    <ul>
                                                        <li><a>Blue</a></li>
                                                        <li><a>Green</a></li>
                                                        <li><a>Neutrals</a></li>
                                                        <li><a>Pink</a></li>
                                                        <li><a>White</a></li>
                                                    </ul>
                                                </div>
                                                <div class="dropdown-category-item">
                                                    <div class="dropdown-category-title">
                                                        Product Type
                                                    </div>
                                                    <ul>
                                                        <li><a>Shorts</a></li>
                                                        <li><a>Shirt L/S</a></li>
                                                        <li><a>Shirt S/S</a></li>
                                                        <li><a>Pants</a></li>
                                                        <li><a>Dress</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown-content">
                                            <div class="dropdown-content-info">
                                                <h4>See 122 results for "Volley Short"</h4>
                                                <span
                                                    class="dropdown-content-icon"><svg
                                                        viewBox="0 0 56 56"
                                                        style="width: 14px;height: 14px;"
                                                        xmlns="http://www.w3.org/2000/svg">
                                                        <path
                                                            d="M45.34 29.564l-25.785 25.785c-0.869 0.869-2.259 0.869-3.128 0l-5.768-5.768c-0.869-0.869-0.869-2.259 0-3.128l18.452-18.452-18.452-18.452c-0.869-0.869-0.869-2.259 0-3.128l5.768-5.768c0.869-0.869 2.259-0.869 3.128 0l25.785 25.785c0.869 0.869 0.869 2.259 0 3.128z"></path>
                                                    </svg></span>
                                            </div>
                                            <div class="dropdown-content-title">
                                                <h4>Product Suggestions</h4>
                                            </div>
                                            <div class="dropdown-content-results">
                                                <?php for ($i = 0; $i < 12; $i++): ?>
                                                    <div class="content-result">
                                                        <img
                                                            src="https://cdn.shopify.com/s/files/1/0004/3686/3040/files/QuincyJacket-AlmondTan_600x600.jpg?v=1710987482">
                                                        <div class="result-details">
                                                            <div
                                                                class="result-details-title"><a href="#">Quince
                                                                    Jacket</a></div>
                                                            <div
                                                                class="product-item-price">$169.95</div>

                                                        </div>
                                                    </div>
                                                <?php endfor ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="search-close">
                                <svg viewBox="0 0 16 14">
                                    <path d="M15 0L1 14m14 0L1 0" stroke="currentColor" fill="none" fill-rule="evenodd"></path>
                                </svg>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li><a>STORES</a></li>
            <li><a>ACCOUNT</a></li>
            <li><a>REWARDS</a></li>
            <li><a>WISHLIST</a></li>
            <li><a class="header-cart">CART(1)</a></li>
        </ul>
    </div>
</div>
<div class="sidebar-cart" id="cart">
    <div class="drawer-header">
        <div class="drawer-title">
            CART
        </div>
        <button class="drawer-close">
            <svg class="Icon Icon--close" role="presentation"
                viewBox="0 0 16 14">
                <path d="M15 0L1 14m14 0L1 0" stroke="currentColor"
                    fill="none" fill-rule="evenodd"></path>
            </svg>

        </button>
    </div>
    <div class="drawer-content">
        <div
            style="flex-direction:column; background:#dcc1a3; color: #FFFFFF; ">
            <div class="cart-banner-main">
                ACADEMY REWARDS </div>
            <div class=" cart-banner-body">
                <div class=" cart-banner-blocks"
                    style="flex-direction: column; ">
                    <div class="cart-banner-block earn"
                        style="color:white;"> $10 reward</div>
                    <div class="cart-banner-block"
                        style="color: white;"> earned when you sign
                        up
                    </div>
                </div>

                <div class=" cart-banner-blocks"
                    style="flex-direction: column;">
                    <div class="cart-banner-block earn"
                        style="color:white;"> $10 reward</div>
                    <div class="cart-banner-block"
                        style="color: white;"> per $100 spent
                    </div>
                </div>

            </div>
            <div class="cart-collapsible-banner-login">
                <a href
                    class="cart-collapsible-banner-button"
                    style="background:#FFFFFF; color:#dcc1a3;"> Join
                    Now </a>
                <a href
                    class="cart-collapsible-banner-button">
                    Login </a>
            </div>
            <div class="cart-banner-secondary">
                <p>Spend &amp; earn today!</p>
            </div>
        </div>
        <div class="drawer-main">
            <div class="Cart-ShippingNotice">
                <div class="Drawer-Container">
                    <p>Spend $9.05 more and get free shipping!</p>
                </div>
            </div>
            <div class="Drawer-Container">
                <div class="Cart-ItemList">
                    <div class="CartItemWrapper">
                        <div class="CartItem">
                            <div class="CartItem-ImageWrapper">
                                <img
                                    style="height: 175px; width: 125px;"
                                    src="//academybrand.com/cdn/shop/files/TEDSHIRT-SEASPONGE-B_240x.jpg?v=1725508226">
                            </div>
                            <div class="CartItem-Info">
                                <div class="CartItem-Title">
                                    Ted Short Sleeve Shirt
                                </div>
                                <div class="CartItem-Meta">
                                    <div class="CartItem-Variant">
                                        <p>SEASPONGE / XS</p>
                                    </div>
                                    <div class="CartItem-PriceList">
                                        <span
                                            class="CartItem-Price">$89.95</span>
                                        <ul>
                                            <div
                                                class="CartItem-Discount">
                                                Add 1 more to get
                                                Buy 2 or more get
                                                25% off
                                            </div>
                                        </ul>
                                    </div>
                                </div>
                                <div class="CartItem-action">
                                    <div
                                        class="CartItem-QuantitySelector">
                                        <div
                                            class="QuantitySelector"><a
                                                class="QuantitySelector__Button Link Link--primary"
                                                title="Set quantity to 0"
                                                href
                                                data-quantity="0"
                                                data-line="1"
                                                data-action="update-item-quantity"
                                                data-variant-id="40776957001830"
                                                data-operation="subtract"><svg
                                                    class="Icon Icon--minus "
                                                    role="presentation"
                                                    viewBox="0 0 16 2">
                                                    <path
                                                        d="M1,1 L15,1"
                                                        stroke="currentColor"
                                                        fill="none"
                                                        fill-rule="evenodd"
                                                        stroke-linecap="square"></path>
                                                </svg></a>

                                            <input type="text"
                                                name="updates[]"
                                                id="updates_40776957001830:d3dde7b3a0ba769ae66c020e7e49a97c"
                                                class="QuantitySelector__CurrentQuantity"
                                                pattern="[0-9]*"
                                                data-line="1"
                                                value="1"
                                                fdprocessedid="y89g1">
                                            <a
                                                class="QuantitySelector__Button Link Link--primary "
                                                href
                                                data-quantity="2"
                                                data-action="update-item-quantity"
                                                data-operation="add"
                                                data-line="1"
                                                data-variant-id="40776957001830"
                                                title="Set quantity to 2"><svg
                                                    class="Icon Icon--plus "
                                                    role="presentation"
                                                    viewBox="0 0 16 16">
                                                    <g
                                                        stroke="currentColor"
                                                        fill="none"
                                                        fill-rule="evenodd"
                                                        stroke-linecap="square">
                                                        <path
                                                            d="M8,1 L8,15"></path>
                                                        <path
                                                            d="M1,8 L15,8"></path>
                                                    </g>
                                                </svg></a>
                                        </div>
                                    </div>
                                    <a href
                                        class="CartItem-Remove">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="drawer-footer">
        <div class="side-cart">
            <div class="recommendation-header">
                <div class="close-icon">
                    <svg viewBox="0 0 56 56" xmlns="http://www.w3.org/2000/svg">
                        <path d="M56 16.329c0 0.449-0.224 0.954-0.561 1.291l-26.148 26.148c-0.337 0.337-0.842 0.561-1.291 0.561s-0.954-0.224-1.291-0.561l-26.148-26.148c-0.337-0.337-0.561-0.842-0.561-1.291s0.224-0.954 0.561-1.291l2.806-2.806c0.337-0.337 0.786-0.561 1.291-0.561 0.449 0 0.954 0.224 1.291 0.561l22.052 22.052 22.052-22.052c0.337-0.337 0.842-0.561 1.291-0.561s0.954 0.224 1.291 0.561l2.806 2.806c0.337 0.337 0.561 0.842 0.561 1.291z"></path>
                    </svg>
                </div>
                <div class="side-cart-title">
                    How About These?
                </div>
                <div class="carousel-navigation">
                    <div class="carousel-prev">
                        <svg viewBox="0 0 100 100">
                            <path d="M 20,50 L 60,90 L 60,85 L 25,50  L 60,15 L 60,10 Z" class="arrow"></path>
                        </svg>
                    </div>
                    <div class="carousel-next">
                        <svg viewBox="0 0 100 100">
                            <path d="M 20,50 L 60,90 L 60,85 L 25,50  L 60,15 L 60,10 Z" class="arrow" transform="translate(100, 100) rotate(180) "></path>
                        </svg>
                    </div>
                </div>
                <div class="collapse-container">
                    <svg viewBox="0 0 56 56"
                        xmlns="http://www.w3.org/2000/svg">
                        <path d="M56 39.671c0 0.449-0.224 0.954-0.561 1.291l-2.806 2.806c-0.337 0.337-0.786 0.561-1.291 0.561-0.449 0-0.954-0.224-1.291-0.561l-22.052-22.052-22.052 22.052c-0.337 0.337-0.842 0.561-1.291 0.561s-0.954-0.224-1.291-0.561l-2.806-2.806c-0.337-0.337-0.561-0.842-0.561-1.291s0.224-0.954 0.561-1.291l26.148-26.148c0.337-0.337 0.842-0.561 1.291-0.561s0.954 0.224 1.291 0.561l26.148 26.148c0.337 0.337 0.561 0.842 0.561 1.291z"></path>
                    </svg>
                </div>
            </div>
            <div class="recommendation-result">
                <?php for ($i = 0; $i < 10; $i++): ?>
                    <div class="recommendation-item">
                        <div class="item-maincontent">
                            <img src="https://cdn.shopify.com/s/files/1/0004/3686/3040/files/MACTEE-SEASPONGE-A_200x600.jpg?v=1727161488">
                            <div class="item-hoverdetail">
                                <div class="item-selectionlist">
                                    <button class="item-selection active">XS</button>
                                    <button class="item-selection">S</button>
                                    <button class="item-selection">M</button>
                                    <button class="item-selection">L</button>
                                    <button class="item-selection">XL</button>
                                    <button class="item-selection">XXL</button>
                                </div>
                                <button class="item-addtocart">
                                    <span class="text">Add to bag</span>
                                </button>
                            </div>
                            <div class="item-bagbe">
                                Buy 2 Save 25%
                            </div>
                        </div>
                        <div class="item-title">
                            <a>Mac Tee</a>
                        </div>
                        <div class="item-name">
                            <a>SEASPONGE</a>
                        </div>
                        <div class="item-price">
                            <a>$49.85</a>
                        </div>
                    </div>
                <?php endfor ?>
            </div>
        </div>

        <button type="button">Add Order Note</button>
        <p>Shipping & taxes calculated at checkout</p>
        <div class="hulk-wishlist-icon">
            <a href="#" class="hulk-header-icon">
                <i class="fa fa-heart-o" aria-hidden="true"></i>
            </a>
        </div>
        <div class="slideshow-button">
            <a href class="buttongroup-item">
                <span>Checkout</span>
                <span class="Button-SeparatorDot"></span>
                <span>AU $89.95</span>
            </a>
        </div>

    </div>
</div>

<script>
    require(['jquery', 'slick'], function($) {
        $(document).ready(function() {

            // toggle megamenu
            $('.header-list-items').mouseenter(function() {
                $('.megamenu').removeClass('is-expanded');
                $(this).siblings('.megamenu').addClass('is-expanded');
            });

            $('.header_left_text').mouseleave(function() {
                $('.megamenu').removeClass('is-expanded');
            });

            // show cart
            $('.header-cart').on("click", function() {
                $('#cart').addClass("showcart");
                $('#overlay').toggle();
            });
            // close cart
            $('.drawer-close, #overlay').on('click', function() {
                $('#cart').removeClass("showcart");
                $('#overlay').toggle();
            })

            //show side-cart
            $('.side-cart-title, .collapse-container, .close-icon').on("click", function() {
                $('.drawer-main').toggleClass("hidden");
                $('.collapse-container').toggle();
                $('.close-icon').toggle();
                $('.carousel-navigation').toggle();
                if ($('.carousel-navigation').css('display') === 'block') {
                    $('.carousel-navigation').css('display', 'flex');
                }
                $('.recommendation-result').toggleClass("show");
            });

            $('.item-selection').on('click', function() {
                $(this).siblings('.item-selection').removeClass('active');
                $(this).addClass('active');
            })

            // slick
            $('.recommendation-result').slick({
                dots: false,
                infinite: false,
                speed: 500,
                slidesToShow: 2,
                slidesToScroll: 2,
                arrows: true,
                prevArrow: $('.carousel-prev'),
                nextArrow: $('.carousel-next')
            });

            $('.search-btn, .search-close').on('click', function() {
                $("#search").toggleClass("active");
                $(".search-dropdown").toggleClass("active");
                setTimeout(function() {
                    $('.dropdown-content-results').slick('setPosition');
                }, 1000);
            })

            $('.dropdown-content-results').slick({
                dots: false,
                infinite: false,
                speed: 500,
                slidesToShow: 4,
                slidesToScroll: 2,
                arrows: false
            });



        });
    });
</script>