<div class="carousel-main">
    <div class="carousel-title"><strong>Compatible Accessories</strong></div>
    <div class="carousel-container">
        <div class="buttonspace">
            <button type="button" class="carousel-class-prev"></button>
        </div>
        <div class="your-carousel-class">
            <div class="product-item-info">
                <img src="<?= $block->getViewFileUrl('images/issho_coffee_table.png') ?>" alt="Image 1">
                <div class="secondary-addto-links">
                    <a class="towishlist" href="#">
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </a>
                </div>
                <a class="product-item-name" href="#">
                    <strong>Issho</strong> Coffee Table
                </a>
                <div class="price-box">
                    <span class="text-price">Full Price From </span>
                    <span class="price"><strong>$1,488</strong></span>
                </div>
            </div>
            <div class="product-item-info">
                <img src="<?= $block->getViewFileUrl('images/pansquare-1_5.jpg') ?>" alt="Image 1">
                <div class="secondary-addto-links">
                    <a class="towishlist" href="#">
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </a>
                </div>
                <a class="product-item-name" href="#">
                    <strong>Panama</strong> Cushion Square
                </a>
                <div class="price-box">
                    <span class="text-price">Full Price From </span>
                    <span class="price"><strong>$99</strong></span>
                </div>
            </div>
            <div class="product-item-info">
                <img src="<?= $block->getViewFileUrl('images/apero_coffee_table_round.png') ?>" alt="Image 1">
                <div class="secondary-addto-links">
                    <a class="towishlist" href="#">
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </a>
                </div>
                <a class="product-item-name" href="#">
                    <strong>Apero</strong> Coffee table round
                </a>
                <div class="price-box">
                    <span class="text-price">Full Price From </span>
                    <span class="price"><strong>$946</strong></span>
                </div>
            </div>
            <div class="product-item-info">
                <img src="<?= $block->getViewFileUrl('images/rugkl-underlay-square.jpg') ?>" alt="Image 1">
                <div class="secondary-addto-links">
                    <a class="towishlist" href="#">
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </a>
                </div>
                <a class="product-item-name" href="#">
                    <strong>Rug</strong> Underlay 260X350cm
                </a>
                <div class="price-box">
                    <span class="text-price">Full Price From </span>
                    <span class="price"><strong>$319</strong></span>
                </div>
            </div>
            <div class="product-item-info">
                <img src="<?= $block->getViewFileUrl('images/images.jpg') ?>" alt="Image 1">
                <div class="secondary-addto-links">
                    <a class="towishlist" href="#">
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </a>
                </div>
                <a class="product-item-name" href="#">
                    <strong>Bolster Armrest</strong> – Jasper & Kato
                </a>
                <div class="price-box">
                    <span class="text-price">Full Price From </span>
                    <span class="price"><strong>$218</strong></span>
                </div>
            </div>
        </div>
        <div class="buttonspace">
            <button type="button" class="carousel-class-next"></button>
        </div>
    </div>
</div>
<script>
    require(['jquery', 'slick'], function($) {
        $('.your-carousel-class').slick({
            dots: true,
            infinite: true,
            speed: 500,
            slidesToShow: 3,
            slidesToScroll: 1,
            arrows: true,
            prevArrow: $('.carousel-class-prev'),
            nextArrow: $('.carousel-class-next'),
            responsive: [{
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: 2.5,
                        slidesToScroll: 1,
                        infinite: false
                    }
                },
                {
                    breakpoint: 800,
                    settings: {
                        slidesToShow: 1.5,
                        slidesToScroll: 1,
                        infinite: false
                    }
                },
                {
                    breakpoint: 500,
                    settings: {
                        slidesToShow: 1, 
                        slidesToScroll: 1
                    }
                }
            ]
        });
    });
</script>