<div class="CollectionFilters">
    <div class="Collection__Header">
        <span class="Collection__Header-header">Filter</span>
        <button class="Collection__Close">
            <svg class="Icon Icon--close" role="presentation" viewBox="0 0 16 14">
                <path d="M15 0L1 14m14 0L1 0" stroke="currentColor" fill="none" fill-rule="evenodd"></path>
            </svg>
        </button>
    </div>
    <div class="Collection__Content">
        <div class="Collection__Content-accordion">
            <div class="Collection__Main">
                <div class="Collection_Main-item" data-role="collapsible">
                    <div class="Collection_Button" data-role="trigger">Colour
                        <span class="Collection_Plus"></span>
                    </div>
                    <div class="panel" data-role="content">
                        <ul>
                            <li>
                                <input type="checkbox" name="name1"><label>Blue</label>
                            </li>
                            <li>
                                <input type="checkbox" name="name1"><label>Neutrals</label>
                            </li>
                            <li><input type="checkbox" name="name1"><label>Green</label>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="Collection__Main">
                <div class="Collection_Main-item" data-role="collapsible">
                    <div class="Collection_Button" data-role="trigger">Colour
                        <span class="Collection_Plus"></span>
                    </div>
                    <div class="panel" data-role="content">
                        <ul>
                            <li>
                                <input type="checkbox" name="name1"><label>Blue</label>
                            </li>
                            <li>
                                <input type="checkbox" name="name1"><label>Neutrals</label>
                            </li>
                            <li><input type="checkbox" name="name1"><label>Green</label>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="Collection__Main">
                <div class="Collection_Main-item" data-role="collapsible">
                    <div class="Collection_Button" data-role="trigger">Colour
                        <span class="Collection_Plus"></span>
                    </div>
                    <div class="panel" data-role="content">
                        <ul>
                            <li>
                                <input type="checkbox" name="name1"><label>Blue</label>
                            </li>
                            <li>
                                <input type="checkbox" name="name1"><label>Neutrals</label>
                            </li>
                            <li><input type="checkbox" name="name1"><label>Green</label>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="Collection__Main">
                <div class="Collection_Main-item" data-role="collapsible">
                    <div class="Collection_Button" data-role="trigger">Colour
                        <span class="Collection_Plus"></span>
                    </div>
                    <div class="panel" data-role="content">
                        <ul>
                            <li>
                                <input type="checkbox" name="name1"><label>Blue</label>
                            </li>
                            <li>
                                <input type="checkbox" name="name1"><label>Neutrals</label>
                            </li>
                            <li><input type="checkbox" name="name1"><label>Green</label>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="Collection__Footer">
            <button class="footer-btn">See Results</button>
        </div>
    </div>

</div>
</div>

<div class="PageHeader">
    <div class="Container">
        <div class="SectionHeader">
            <div class="SectionHeader_Heading">
                Men's Shorts
            </div>
            <div class="SectionHeader_Description">
                <div class="expanded-modal">
                    <div class="expanded-modal-text">
                        <p class="p1">The Academy Brand men’s shorts come in different styles, fabrics and colours—perfect for the warm weather or a casual getaway. Whether you’re going for a relaxe...</p>
                    </div>

                    <button class="btn-readmore">
                        <span class="icon-arrow-down"><svg class="Icon Icon--select-arrow" role="presentation" viewBox="0 0 19 12">
                                <polyline fill="none" stroke="currentColor" points="17 2 9.5 10 2 2" fill-rule="evenodd" stroke-width="2" stroke-linecap="square"></polyline>
                            </svg></span>
                        <span class="link">Read More</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="CategoryMain">
    <div class="CategoryList">
        <div class="CategoryToolbar">
            <div class="CategoryToolbar_Item">
                <button class="CategoryToolbar_Layout active">
                    <svg class="Icon Icon--wall-2" role="presentation" viewBox="0 0 36 36">
                        <path fill="currentColor" d="M21 36V21h15v15H21zm0-36h15v15H21V0zM0 21h15v15H0V21zM0 0h15v15H0V0z"></path>
                    </svg>
                </button>
                <button class="CategoryToolbar_Layout">
                    <svg class="Icon Icon--wall-4" role="presentation" viewBox="0 0 36 36">
                        <path fill="currentColor" d="M28 36v-8h8v8h-8zm0-22h8v8h-8v-8zm0-14h8v8h-8V0zM14 28h8v8h-8v-8zm0-14h8v8h-8v-8zm0-14h8v8h-8V0zM0 28h8v8H0v-8zm0-14h8v8H0v-8zM0 0h8v8H0V0z"></path>
                    </svg>
                </button>
            </div>
            <div class="CategoryToolbar_Group Sort_Filter">
                <div class="CategoryToolbar_Item Sort">
                    Sort
                    <svg class="CategoryToolbar_btn Icon Icon--select-arrow" role="presentation" viewBox="0 0 19 12">
                        <polyline fill="none" stroke="currentColor" points="17 2 9.5 10 2 2" fill-rule="evenodd" stroke-width="2" stroke-linecap="square"></polyline>
                    </svg>
                    <div class="Category_Short_Popover">
                        <div class="Popover_Header">
                            <button class="CategoryToolber_Close">
                                <svg class="Icon" role="presentation" viewBox="0 0 16 14">
                                    <path d="M15 0L1 14m14 0L1 0" stroke="currentColor" fill="none" fill-rule="evenodd"></path>
                                </svg>
                            </button>
                            Sort
                        </div>
                        <div class="Popover_Content">
                            <div class="Popover_ValueList">
                                <button class="Popover_Value">
                                    Academy Picks
                                </button>
                                <button class="Popover_Value">
                                    Popular
                                </button>
                                <button class="Popover_Value">
                                    Cheatest First
                                </button>
                                <button class="Popover_Value">
                                    Highest Price First
                                </button>
                                <button class="Popover_Value">
                                    NEW In
                                </button>
                                <button class="Popover_Value">
                                    Top Rated
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="CategoryToolbar_Item CategoryToolbar_Filter">
                    Filter
                </div>
            </div>
        </div>
        <div class="CategoryInner">
            <div class="CategoryInner_Products">
                <div class="ProductListWrapper">
                    <div class="ProductList">
                        <?php for ($i = 0; $i < 40; $i++): ?>
                            <div class="ProductItem">
                                <div class="category-item">
                                    <div class="item-maincontent">
                                        <img src="<?= $block->getViewFileUrl('images/COOPERCHINOSHORT-CHARCOAL-B_400x600.webp')  ?>">
                                        <div class="item-hoverdetail">
                                            <div class="item-selectionlist">
                                                <button class="item-selection active">28</button>
                                                <button class="item-selection">30</button>
                                                <button class="item-selection">32</button>
                                                <button class="item-selection">34</button>
                                                <button class="item-selection">36</button>
                                                <button class="item-selection">38</button>
                                                <button class="item-selection disabled">40</button>
                                            </div>
                                            <button class="item-addtocart">
                                                <span class="text">Add to bag</span>
                                            </button>
                                        </div>
                                        <div class="item-bagbe">
                                            New
                                        </div>
                                        <div class="item-bagbe-secondary">
                                            25% Off
                                        </div>
                                        <div class="wishlist-icon">
                                            <i class="fa fa-heart-o" aria-hidden="true"></i>
                                        </div>
                                        <div class="product-item-mobileaddtocart">
                                            <svg
                                                class="Icon Icon--mobile-bag "
                                                role="presentation"
                                                viewBox="0 0 132.56 132.56">
                                                <circle
                                                    style="stroke-width: 0px;  fill: #fff; opacity: .8;"
                                                    class="cls-2"
                                                    cx="66.28"
                                                    cy="66.28"
                                                    r="66.28"></circle>
                                                <path
                                                    style="stroke-width: 0px; fill: #010101;"
                                                    class="cls-1"
                                                    d="M42.91,92.77v-41.25l2.75.02v.04h11v-2.79c0-6.83,3.5-11,9.62-11,5.55,0,9.62,4.07,9.62,11v2.78h13.75s0,2.7,0,2.7h-43.99v35.76h41.24v-35.73h2.75v38.48h-46.74ZM73.15,50.13c0-6.11-1.36-9.59-6.87-9.59s-6.87,3.49-6.87,9.59v1.4h13.75v-1.4Z"></path>
                                            </svg>
                                        </div>
                                    </div>
                                    <div class="item-title">
                                        <a>Mac Tee</a>
                                    </div>
                                    <div class="item-name">
                                        <a>SEASPONGE</a>
                                    </div>
                                    <div class="item-price">
                                        <a>$49.85</a>
                                    </div>
                                </div>
                            </div>
                        <?php endfor ?>
                    </div>
                </div>
                <div class="Pagination">
                    <div class="Pagination__Nav">
                        <a href="#" class="Pagination__NavItem active">1</a><a href="#" class="Pagination__NavItem">2</a><a href="#" class="Pagination__NavItem">3</a><a href="#" class="Pagination__NavItem">
                            <svg role="presentation" viewBox="0 0 11 18" class="Icon Icon--select-arrow-right">
                                <path d="M1.5 1.5l8 7.5-8 7.5" stroke-width="2" stroke="currentColor" fill="none" fill-rule="evenodd" stroke-linecap="square"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="Recommendation">
    <div class="Recommendation__Header">
        <div class="Recommendation__Title">
            Recently Viewed
        </div>
    </div>
    <div class="Recommendation__Result">
        <div class="Recommendation__Profile">
            <?php for ($i = 0; $i < 12; $i++): ?>
                <div class="ProductItem">
                    <div class="category-item">
                        <div class="item-maincontent">
                            <img src="<?= $block->getViewFileUrl('images/COOPERCHINOSHORT-CHARCOAL-B_400x600.webp')  ?>">
                            <div class="item-hoverdetail">
                                <div class="item-selectionlist">
                                    <button class="item-selection active">XS</button>
                                    <button class="item-selection">S</button>
                                    <button class="item-selection">M</button>
                                    <button class="item-selection">L</button>
                                    <button class="item-selection">XL</button>
                                    <button class="item-selection">XXL</button>
                                </div>
                                <button class="item-addtocart">
                                    <span class="text">Add to bag</span>
                                </button>
                            </div>
                            <div class="item-bagbe">
                                New
                            </div>
                            <div class="item-bagbe-secondary">
                                25% Off
                            </div>
                            <div class="wishlist-icon">
                                <i class="fa fa-heart-o" aria-hidden="true"></i>
                            </div>
                            <div class="product-item-mobileaddtocart">
                                <svg
                                    class="Icon Icon--mobile-bag "
                                    role="presentation"
                                    viewBox="0 0 132.56 132.56">
                                    <circle
                                        style="stroke-width: 0px;  fill: #fff; opacity: .8;"
                                        class="cls-2"
                                        cx="66.28"
                                        cy="66.28"
                                        r="66.28"></circle>
                                    <path
                                        style="stroke-width: 0px; fill: #010101;"
                                        class="cls-1"
                                        d="M42.91,92.77v-41.25l2.75.02v.04h11v-2.79c0-6.83,3.5-11,9.62-11,5.55,0,9.62,4.07,9.62,11v2.78h13.75s0,2.7,0,2.7h-43.99v35.76h41.24v-35.73h2.75v38.48h-46.74ZM73.15,50.13c0-6.11-1.36-9.59-6.87-9.59s-6.87,3.49-6.87,9.59v1.4h13.75v-1.4Z"></path>
                                </svg>
                            </div>
                        </div>
                        <div class="item-title">
                            <a>Mac Tee</a>
                        </div>
                        <div class="item-name">
                            <a>SEASPONGE</a>
                        </div>
                        <div class="item-price">
                            <a>$49.85</a>
                        </div>
                    </div>
                </div>
            <?php endfor ?>
        </div>
    </div>
</div>

<!-- <script>
    require(['jquery', 'slick', 'accordion'], function($) {
        $(document).ready(function() {
            $('.btn-readmore').on('click', function() {
                var currrentContent = $('.expanded-modal-text').html().trim();

                var shortContent = '<p class="p1">The Academy Brand men’s shorts come in different styles, fabrics and colours—perfect for the warm weather or a casual getaway. Whether you’re going for a relaxe...</p>';
                var expandedContent = `
                    <p class="p1">The Academy Brand men’s shorts come in different styles, fabrics and colours—perfect for the warm weather or a casual getaway. Whether you’re going for a relaxed, sporty or smart look, our collection of shorts has something for every occasion.</p>
                    <p class="p1">Our chino short have a button up fixed waist and are garment dyed and enzyme washed, giving them a lovely soft feel. These shorts will quickly become your summer essential when paired with a simple tee or <a href="https://academybrand.com/collections/s-s-shirts"><span class="s1">linen shirt</span></a>.</p>
                    <p class="p1">The volley short is another classic summer staple that gives extra comfort with its elastic waistband and natural cotton drawcord. Like the chino shorts, this pair is enzyme washed for that premium soft feel. Easily pair with a <a href="https://academybrand.com/collections/mens-long-sleeve-shirts"><span class="s1">shirt with rolled up sleeves</span></a> or a <a href="https://academybrand.com/collections/mens-tees-and-layering"><span class="s1">cotton tee</span></a>. If you’re after an effortlessly cool look with contemporary styling, the cotton sweat is made for you. Wear with a loose fit tee or oversized long sleeve tee for a sporty getup.</p>
                    <p class="p1">As for our linen shorts, these can be dressed up or down to suit the occasion. Linen is great in the hot weather because it's lightweight, breathable and will soften with every wash and wear.</p>
                    <p class="p1">The Academy Brand shorts collection will have you ready for any holiday, adventure or even everyday errands. Shop our shorts and find the next pair to add to your wardrobe.</p>
                `;

                var readMore = `Read More`;
                var showLess = `Show Less`;
                if (currrentContent == shortContent) {
                    $('.expanded-modal-text').slideUp('slow', function() {
                        $('.expanded-modal-text').html(expandedContent);

                        $('.expanded-modal-text').slideDown('slow');
                        $('.link').html(showLess);
                        $('.Icon').css('transform', 'rotate(180deg)');

                    });
                } else {
                    $('.expanded-modal-text').slideUp('slow', function() {
                        $('.expanded-modal-text').html(shortContent);
                        $('.expanded-modal-text').slideDown('slow');
                        $('.link').html(readMore);
                        $('.Icon').css('transform', 'rotate(360deg)');

                    });
                }
            })
            //Filter
            $(".Collection__Main").accordion({
                collapsible: true,
                active: false,
            });
            $('.Collection_Button').on('click',function(){
                $(this).toggleClass('active');
            })
            //cagegory
            $('.Recommendation__Profile').slick({
                dots: false,
                infinite: false,
                slidesToShow: 5,
                responsive: [{
                        breakpoint: 1240,
                        settings: {
                            slidesToShow: 4,
                        }
                    },
                    {
                        breakpoint: 1024,
                        settings: {
                            slidesToShow: 3,
                        }
                    },
                    {
                        breakpoint: 540,
                        settings: {
                            slidesToShow: 2,
                        }
                    }
                ]
            });


            $('.CategoryToolbar_Filter, .Collection__Close').on('click', function() {
                $('.CollectionFilters').addClass('show');
                $('#overlay').toggle();
            })
            $('.item-selection').on('click', function() {
                if (!$(this).hasClass('disabled')) {
                    $(this).siblings('.item-selection').removeClass('active');
                    $(this).addClass('active');
                }
            })


            // Sort
            $('.CategoryToolbar_Item.Sort').on('click', function(e) {
                e.stopPropagation();
                $('.Category_Short_Popover').toggleClass('show');
            })
            $('.CategoryToolber_Close').on('click', function(e) {
                e.stopPropagation();
                $('.Category_Short_Popover').removeClass('show');
            })
            $(document).on('click', function(e) {
                if (!$(e.target).closest('.Category_Short_Popover').length)
                    $('.Category_Short_Popover').removeClass('show');
            });

            $('.CategoryToolbar_Layout').on('click', function() {
                $('.CategoryToolbar_Layout').removeClass('active');
                $(this).addClass("active");
            })
        });
    });
</script> -->
