<style>
    .carousel-class-prev,
    .carousel-class-next {
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        z-index: 1;
        font-size: 18px;
        background-color: black;
        border: 1px solid black;
        border-radius: 50%;
        width: 50px;
        height: 50px;
        /* padding: 5px 10px; */
    }
    /* .carousel-class-prev{
        left: -10px;
    }
    .carousel-class-next{
        right: 10px;
    } */
    .slick-prev:hover,
    .slick-next:hover {
        background: gray;
    }
</style>

<div class="carousel-container">
<button type="button" class="carousel-class-prev">Previous</button>
    <div class="your-carousel-class">
        <div><img src="<?= $block->getViewFileUrl('images/images.jpg') ?>" alt="Image 1"></div>
        <div><img src="<?= $block->getViewFileUrl('images/images.jpg') ?>" alt="Image 2"></div>
        <div><img src="<?= $block->getViewFileUrl('images/images.jpg') ?>" alt="Image 3"></div>
        <div><img src="<?= $block->getViewFileUrl('images/images.jpg') ?>" alt="Image 3"></div>
        <div><img src="<?= $block->getViewFileUrl('images/images.jpg') ?>" alt="Image 3"></div>
        <div><img src="<?= $block->getViewFileUrl('images/images.jpg') ?>" alt="Image 3"></div>
    </div>
    <button type="button" class="carousel-class-next">Next</button>
</div>
<script>
    require(['jquery', 'slick'], function($) {
        $('.your-carousel-class').slick({
            dots: true,
            infinite: true,
            speed: 500,
            slidesToShow: 3,
            slidesToScroll: 1,
            arrows: true,
            prevArrow: '<button type="button" class="carousel-class-prev">Previous</button>',
            nextArrow: '<button type="button" class="carousel-class-next">Next</button>'
        });
    });
</script>